### ISSUE TITLE
issues in eval_TextGrph.py

### ISSUE THREAD

**Issue by haazelnuter** [GXYM/DRRG#37]
when i try to run eval_TextGrph.py i got this , even if retrained model , and im using GPU 
THCudaCheck FAIL file=/tmp/pip-req-build-58y_cjjl/aten/src/THC/THCGeneral.cpp line=50 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "eval_TextGraph.py", line 206, in <module>
    main(vis_dir)
  File "eval_TextGraph.py", line 165, in main
    model = model.to(cfg.device)
  File "/home/xx/.conda/envs/drrg_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/home/xx/.conda/envs/drrg_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/xx/.conda/envs/drrg_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/xx/.conda/envs/drrg_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/xx/.conda/envs/drrg_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/xx/.conda/envs/drrg_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/xx/.conda/envs/drrg_env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 179, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /tmp/pip-req-build-58y_cjjl/aten/src/THC/THCGeneral.cpp:50

**Comment by haazelnuter** [comment]
i solved problem
